--SEQUENCES
DROP SEQUENCE IF EXISTS NOTIFICATIONS_SEQ;
DROP SEQUENCE IF EXISTS CHANNELS_SEQ;
DROP SEQUENCE IF EXISTS SUBSCRIBED_SEQ;
DROP SEQUENCE IF EXISTS USERS_SEQ;

CREATE SEQUENCE USERS_SEQ START 1;
CREATE SEQUENCE SUBSCRIBED_SEQ START 1;
CREATE SEQUENCE CHANNELS_SEQ START 1;
CREATE SEQUENCE NOTIFICATIONS_SEQ START 1;

--TABLES
DROP TABLE IF EXISTS NOTIFICATIONS;
DROP TABLE IF EXISTS CHANNELS;
DROP TABLE IF EXISTS SUBSCRIBED;
DROP TABLE IF EXISTS USERS;

create table USERS(
    user_id INT NOT NULL DEFAULT nextval('USERS_SEQ'),
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    phone_number VARCHAR(14),
    PRIMARY KEY(user_id)
);

create table SUBSCRIBED (
    subscribed_id INT NOT NULL DEFAULT nextval('SUBSCRIBED_SEQ'),
    user_id INT NOT NULL,
    category VARCHAR(255) NOT NULL,
    UNIQUE (user_id, category),
    PRIMARY KEY(subscribed_id),
    CONSTRAINT fk_user FOREIGN KEY(user_id) REFERENCES USERS(user_id)
);

create table CHANNELS (
    channel_id INT NOT NULL DEFAULT nextval('CHANNELS_SEQ'),
    user_id INT NOT NULL,
    notification_type VARCHAR(255) NOT NULL,
    UNIQUE (user_id, notification_type),
    PRIMARY KEY(channel_id),
    CONSTRAINT fk_user FOREIGN KEY(user_id) REFERENCES USERS(user_id)
);

create table NOTIFICATIONS (
    notification_id INT NOT NULL DEFAULT nextval('NOTIFICATIONS_SEQ'),
    user_id INT NOT NULL,
    category VARCHAR(255) NOT NULL,
    notification_type VARCHAR(255) NOT NULL,
    notification_date TIMESTAMP NOT NULL DEFAULT CURRENT_DATE,
    message VARCHAR(4000) NOT NULL,
    PRIMARY KEY(notification_id),
    CONSTRAINT fk_user FOREIGN KEY(user_id) REFERENCES USERS(user_id)
);

